version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tibia-lobby-api-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: tibia-lobby
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678